2024-01-22 14:30:06,019 INFO    MainThread:116 [wandb_setup.py:_flush():71] setting env: {}
2024-01-22 14:30:06,019 WARNING MainThread:116 [wandb_setup.py:_flush():71] could not save program above cwd: /aiarena/nas/18_data/jiangy/RPSF/transformer/src/train.py
2024-01-22 14:30:06,020 INFO    MainThread:116 [wandb_setup.py:_flush():71] setting login settings: {}
2024-01-22 14:30:06,020 INFO    MainThread:116 [wandb_init.py:_log_setup():357] Logging user logs to /aiarena/nas/18_data/jiangy/RPSF/transformer/src/env/dmc2gym/wandb/run-20240122_143005-1tt2q8ss/logs/debug.log
2024-01-22 14:30:06,020 INFO    MainThread:116 [wandb_init.py:_log_setup():358] Logging internal logs to /aiarena/nas/18_data/jiangy/RPSF/transformer/src/env/dmc2gym/wandb/run-20240122_143005-1tt2q8ss/logs/debug-internal.log
2024-01-22 14:30:06,022 INFO    MainThread:116 [wandb_init.py:init():390] calling init triggers
2024-01-22 14:30:06,022 INFO    MainThread:116 [wandb_init.py:init():395] wandb.init called with sweep_config: {}
config: {}
2024-01-22 14:30:06,023 INFO    MainThread:116 [wandb_init.py:init():435] starting backend
2024-01-22 14:30:06,023 INFO    MainThread:116 [backend.py:_multiprocessing_setup():94] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-01-22 14:30:06,038 INFO    MainThread:116 [backend.py:ensure_launched():198] starting backend process...
2024-01-22 14:30:06,069 INFO    MainThread:116 [backend.py:ensure_launched():203] started backend process with pid: 187
2024-01-22 14:30:06,072 INFO    MainThread:116 [wandb_init.py:init():444] backend started and connected
2024-01-22 14:30:06,075 INFO    MainThread:116 [wandb_init.py:init():503] updated telemetry
2024-01-22 14:30:06,076 INFO    MainThread:116 [wandb_init.py:init():533] communicating current version
2024-01-22 14:30:07,781 INFO    MainThread:116 [wandb_init.py:init():538] got version response upgrade_message: "wandb version 0.16.2 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-01-22 14:30:07,781 INFO    MainThread:116 [wandb_init.py:init():548] communicating run to backend with 30 second timeout
2024-01-22 14:30:37,782 INFO    MainThread:116 [interface.py:_communicate_run():903] couldn't get run from backend
2024-01-22 14:30:37,815 ERROR   MainThread:116 [wandb_init.py:init():553] backend process timed out
2024-01-22 14:30:37,815 ERROR   MainThread:116 [wandb_init.py:init():562] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2024-01-22 14:30:37,827 ERROR   MainThread:116 [wandb_init.py:init():897] error
Traceback (most recent call last):
  File "/home/wangmr/.conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 870, in init
    run = wi.init()
  File "/home/wangmr/.conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 566, in init
    backend.cleanup()
  File "/home/wangmr/.conda/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 227, in cleanup
    self.interface.join()
  File "/home/wangmr/.conda/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 1048, in join
    super(BackendSender, self).join()
  File "/home/wangmr/.conda/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 596, in join
    self._communicate_shutdown()
  File "/home/wangmr/.conda/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 1045, in _communicate_shutdown
    _ = self._communicate(record)
  File "/home/wangmr/.conda/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 799, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/wangmr/.conda/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 804, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
